apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ayd-webapp-ingress
  namespace: aydapp
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx

  tls:
  - hosts:
      - aydapps.dain.com
    secretName: kids-shared-tls

  rules:
  - host: aydapps.dain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ayd-webapp-service
            port:
              number: 80
