apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-app
  namespace: payment-app
spec:
  rules:
    - host: payment.apps.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment-app
                port:
                  number: 80
