apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payment-app

resources:
  - mongo/deployment.yaml
  - mongo/service.yaml
  - web/deployment.yaml
  - web/service.yaml
  - web/ingress.yaml
  - shared/configmap.yaml
  - shared/secret.yaml
