apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongo-deployment.yaml
  - mongo-service.yaml
  - payment-web-deployment.yaml
  - payment-web-service.yaml
  - configmap.yaml
  - secret.yaml
