# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: apps-ingress
#   namespace: web-app
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: apps.local
#       http:
#         paths:
#           - path: /web
#             pathType: Prefix
#             backend:
#               service:
#                 name: web-app
#                 port:
#                   number: 80

#           - path: /token
#             pathType: Prefix
#             backend:
#               service:
#                 name: token-app
#                 port:
#                   number: 80

#           - path: /payment
#             pathType: Prefix
#             backend:
#               service:
#                 name: payment-app
#                 port:
#                   number: 80
