apiVersion: apps/v1
kind: Deployment
metadata:
  name: kids-app
  namespace: token-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kids-app
  template:
    metadata:
      labels:
        app: kids-app
    spec:
      containers:
        - name: kids-app
          image: dainmusty/kids-website:latest       
          ports:
            - containerPort: 8080
