apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kids-app
  namespace: kids-app
spec:
  ingressClassName: nginx
  rules:
    - host: kids.apps.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kids-app
                port:
                  number: 80
