apiVersion: v1
kind: Service
metadata:
  name: kids-app
  namespace: kids-app
spec:
  selector:
    app: kids-app
  ports:
    - port: 80          # ingress talks to this
      targetPort: 8080  # forward to container port
  type: ClusterIP
